jobs:
  build_kirin710:
    machine: true
    image: ubuntu-2004:current
    working_directory: ~/halium
    environment:
      DEVICE: kirin710
      ANDROID_ROOT: ~/halium
    steps:
      - checkout
      - run:
          name: Initialization environment
          command: |
            sudo apt update
            sudo apt-get install -y \
            git gnupg flex ccache bison gperf build-essential \
            zip bzr curl libc6-dev x11proto-core-dev \
            libgl1-mesa-dev g++-multilib tofrodos \
            python3-markdown libxml2-utils xsltproc schedtool \
            liblz4-tool bc lzop imagemagick libncurses5 rsync \
            python-is-python3
            
      - run:
          name: Download repo
          command: |
            mkdir -p ~/bin
            wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
            chmod +x ~/bin/repo
            sed -i '1s/^#!\/usr\/bin\/env python/#!\/usr\/bin\/env python3/' ~/bin/repo
            git config --global user.name "aymanrgab"
            git config --global user.email "aymanrar2c@gmail.com"
            
      - run:
          name: Downloading source code
          command: |
            source hadk.env
            mkdir -p $ANDROID_ROOT
            cd $ANDROID_ROOT
            repo init -u https://github.com/Halium/android.git -b halium-10.0 --depth=1
            #git clone https://github.com/Exynos7880-Linux/kirin710_local_manifests.git .repo/local_manifests
            repo sync

      - run:
          name: Build Recovery
          command: |
            chmod +x build.sh
            bash build.sh
            tar -czf ~/kirin710.tar.gz ~/halium/out/target/product/kirin710/*.img
      - run:
          name: Check free disk
          when: on_fail
          command: |
            df -h

      - store_artifacts:
          path: ~/kirin710.tar.gz
 
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build_kirin710